### ISSUE TITLE
Request: Support for FM RDS

### ISSUE THREAD

**Issue by totalsecond** [google/radioreceiver#3]
FM RDS would be a great feature. It would be nice to see what the name of the song is that is playing (that is, if the station supports RDS).

Thanks!

**Comment by jtarrio** [comment]
Hi! A year or so ago I experimented with decoding RDS, but I couldn't make it work reliably. Perhaps now that I'm more knowledgeable about DSP I could pull it off, and I'll probably try again, but likely not in the near future :-)

**Comment by K2IE** [comment]
Hi Jason, any chance you might be able to get to this?

**Comment by jtarrio** [comment]
No, I'm not really working on Radio Receiver anymore.
