### ISSUE TITLE
WX Station frequencies are off...

### ISSUE THREAD

**Issue by TheNavyBear** [google/radioreceiver#6]
In Portland, NOAA Weather Radio is broadcast on 162.550 which is supposed to be WX1 (frequencies are out of sequence) but in Radio Receiver 162.550 is WX7. While it doesn't stop me from listening, it does confuse you when you know what the WX #s are supposed to be, and it also throws off the rest of the WX #s. Here is a link to the Wikipedia chart of the frequencies each WX# should be: https://en.wikipedia.org/wiki/Weather_radio#Governmental_weather_radio_services (WX1-7 are the official ones. WX8-10 are NOT official or used by NOAA, but are listed in the chart). Could we make the WX #s point to the right frequencies in a future update please? In an emergency, people need to be able to tune to the right NOAA WX # and not have to guess and search for the right channel. Thank you for your time in this matter.

**Comment by jtarrio** [comment]
I've changed the code to show the correct WX channel name. Unfortunately, since Radio Receiver works with frequencies instead of channels, it means that the channel names are out of sequence. I may change the software to be channel-aware in the future, but not for now...

**Comment by TheNavyBear** [comment]
Thank you so much! It is appreciated. The channel aware would be nice, but at least the WX channels are the right frequencies. Thank you so much!

Robert Berg
berg.rw@icloud.com
